In [1]:
#numpy library
# creating numpy array
import numpy as np
arr=np.array([1,2,3])
print(arr)
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr=np.array((1,2,3))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 2 3]


In [2]:
#accessing array index
import numpy as np
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])
arr2=arr[:2,::2]
print("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [3]:
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [4]:
# BASIC ARRAY OPERATIONS
import numpy as np
 
# defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [5]:
# MATH OPERATIONS ON DATA TYPE ARRAY
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [6]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [7]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [ ]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))